DROP TABLE IF EXISTS TASK; -- Safety check to avoid errors if table exists.
CREATE TABLE TASK (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    STATUS VARCHAR(50),
    DUE_DATE DATE
);
-- Add one row for testing purposes
INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, DUE_DATE) VALUES ('Initial Test Task', 'Testing Insert', 'PENDING', '2025-01-01');